version: "3.6"

services:
  qiksar_db:
    env_file: .env

    container_name: qiksar_db
    image: postgres

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

    restart: always

  qiksar_gql:
    env_file: .env

    image: hasura/graphql-engine:latest
    container_name: qiksar_gql

    links:
      - qiksar_db

    ports:
      - "7123:8080"

    command:
      - graphql-engine
      - serve

    restart: always

  # Use this if you want to build the app into a container that you can run from the docker
  qiktrak:
    env_file: .env
    environment:
      - HASURA_GRAPHQL_ENDPOINT=http://qiksar_gql:8080

    container_name: qiksar
    image: qiksar/qiktrak:latest

    build:
      context: .
      dockerfile: ./Dockerfile

    links:
      - qiksar_db
      - qiksar_gql

    command:
      - node
      - qik-trak-cli.js
