version: "3.6"

services:
  qiktrak_db:
    env_file: .env

    container_name: qiktrak_db
    image: postgres

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

    ports:
      - "7001:5432"

    restart: always

  qiktrak_gql:
    env_file: .env

    image: hasura/graphql-engine:latest
    container_name: qiktrak_gql

    links:
      - qiktrak_db

    ports:
      - "7002:8080"

    command:
      - graphql-engine
      - serve

    restart: always

  qik-trak:
    env_file: .env
    environment: 
      - IN_CONTAINER=true

    container_name: qik-trak

    build:
      context: .
      dockerfile: ./Dockerfile

    links:
      - qiktrak_db
      - qiktrak_gql

    command:
      - node
      - cli.js
