version: "3.6"

services:
  qiktrak_db:
    env_file: .env

    container_name: qiktrak_db
    image: postgres

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

    restart: always

  qiktrak_gql:
    env_file: .env

    image: hasura/graphql-engine:latest
    container_name: qiktrak_gql

    links:
      - qiktrak_db

    ports:
      - "7123:8080"

    command:
      - graphql-engine
      - serve

    restart: always

  # Use this if you want to build the app into a container that you can run from docker
  qiktrak:
    env_file: .env
    environment:
      - HASURA_GRAPHQL_ENDPOINT=http://qiktrak_gql:8080

    container_name: qiktrak
    image: qiktrak/qiktrak:latest

    volumes:
      - ./example_db:/example_db

    build:
      context: .
      dockerfile: ./Dockerfile

    links:
      - qiktrak_db
      - qiktrak_gql

    command:
      - node
      - qiktrak-cli.js
